export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-variant": "#e5e2e1",
        "on-tertiary-container": "#551ab6",
        "inverse-surface": "#303030",
        "on-tertiary-fixed-variant": "#561cb7",
        "secondary-container": "#dfe0e0",
        "outline-variant": "#ccc3d2",
        "tertiary": "#6e3dd0",
        "on-primary-container": "#553387",
        "tertiary-container": "#c1a5ff",
        "surface-dim": "#dcd9d9",
        "on-secondary-container": "#616363",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed": "#eddcff",
        "on-secondary-fixed-variant": "#454747",
        "inverse-on-surface": "#f3f0ef",
        "secondary": "#5d5f5f",
        "surface-container-low": "#f6f3f2",
        "outline": "#7b7481",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary-fixed-dim": "#d1bcff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#eaddff",
        "background": "#fcf9f8",
        "primary-fixed-dim": "#d7baff",
        "surface-container-lowest": "#ffffff",
        "surface": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#c8a2ff",
        "primary": "#6f4ca2",
        "on-tertiary-fixed": "#24005b",
        "surface-bright": "#fcf9f8",
        "on-primary-fixed-variant": "#573488",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#e2e2e2",
        "surface-tint": "#6f4ca2",
        "inverse-primary": "#d7baff",
        "on-surface-variant": "#4a4450",
        "on-surface": "#1b1c1c",
        "on-primary-fixed": "#280056",
        "on-secondary": "#ffffff",
        "on-background": "#1b1c1c",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "brand": "20px",
        "pcos": "20px"
      },
      spacing: {
        "unit": "4px",
        "container-padding": "24px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "section-gap": "64px",
        "gutter": "16px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}